# Generated by Django 5.1.7 on 2025-03-19 11:59

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='location',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='route',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='route',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='route',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='routeimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='routeimage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='routeimage',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='routeimage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='routelocation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='routelocation',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='routelocation',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='routelocation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routeimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
