# Generated by Django 5.1.7 on 2025-03-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_remove_comment_deleted_at_remove_comment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routelocation',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='route',
            name='locations',
        ),
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='routes/images/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
