# Generated by Django 5.1.7 on 2025-03-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_remove_comment_route_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
