# Generated by Django 5.1.7 on 2025-03-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_remove_route_image_routeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
