# Generated by Django 5.1.7 on 2025-03-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_alter_route_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='title',
            field=models.CharField(default='Untitled', max_length=255, unique=True),
        ),
    ]
