# Generated by Django 5.1.7 on 2025-04-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_alter_route_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='coordinates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
