# Generated by Django 5.1.7 on 2025-04-15 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_routecoordinate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='coordinates',
        ),
        migrations.AlterField(
            model_name='routecoordinate',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='routes.route'),
        ),
    ]
