# Generated by Django 5.1.7 on 2025-04-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_remove_route_coordinates_alter_routecoordinate_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
