# Generated by Django 5.1.7 on 2025-05-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0013_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
