# Generated by Django 5.1.7 on 2025-05-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0015_remove_route_city_searchlog_viewedroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
